### PR TITLE
[Calculate Area Requirement 01]

### PR DESCRIPTION
**Pull request by IngridPaulino**

### CODE REVIEW

**Review by rosalia-oliveira — APPROVED** [review]

**Review by gabrielmorais-meli — APPROVED** [review]

**Review by amdzotelli — APPROVED** [review]
approve for merge ✅ 💟

**Review by carolhakamada — APPROVED** [review]
Approve! 💟

**Review by marianasaraivameli — APPROVED** [review]
Approve 💛

**Review by rosalia-oliveira — APPROVED** [review]
Aprovado para merge.

**Review by gabrielmorais-meli — APPROVED** [review]

**Review by amdzotelli — APPROVED** [review]

**Pull request merged**
