### PR TITLE
[Price Property Requirement 02]

### PR DESCRIPTION
**Pull request by marianasaraivameli**

### CODE REVIEW

**Review by gabrielmorais-meli — APPROVED** [review]

**Review by IngridPaulino — APPROVED** [review]
💛

**Review by rosalia-oliveira — APPROVED** [review]
Aprovado para merge.

**Review by carolhakamada — APPROVED** [review]
Approve! 💟 ✅

**Review by amdzotelli — APPROVED** [review]
approve for merge ✅ 💟

**Pull request merged**
