### PR TITLE
[Refactor]

### PR DESCRIPTION
**Pull request by rosalia-oliveira**

### CODE REVIEW

**Review by gabrielmorais-meli — APPROVED** [review]

**Review by IngridPaulino — APPROVED** [review]
💛

**Review by carolhakamada — APPROVED** [review]
✅ 💛  Approve!

**Review by marianasaraivameli — APPROVED** [review]
Approve 💛

**Review by amdzotelli — APPROVED** [review]
approve for merge ✅ 💟

**Pull request merged**
